### ISSUE TITLE
Deploy third party library in AC

### ISSUE THREAD

**Issue by teohaik** [istlab/Alitheia-Core#13] opened 2013-11-11 21:36 UTC
Please document the detailed process that should be followed in order to deploy a third party library in alitheia core as an OSGi bundle.

After careful examination of the other approaches, along with @eligu, and by taking into account the AC plugin creation guidelines, we believe that in order to be able to use the libraries that we need, they must be incorporated in AC as a separate OSGi bundle. But after many attempts the result is always a build failure.

Could you provide a detailed guide about the process that should be followed for the successful configuration of the pom.xml and osgi.bnd files?

**Comment by modernist** [comment] 2013-11-11 22:06
Not all external referenced libraries need to be bundled as separate OSGi bundles. This is required only when these 3rd party libraries need to load classes defined in AC bundles via the classloader, because each bundle is loaded by its own classloader in OSGi. For more details check out the OSGi reference found at http://www.osgi.org/Download/HomePage

**Comment by eligu** [comment] 2013-11-11 22:27
@gousiosg @dspinellis 

To explain what @teohaik is requesting I will try to provide the info of what we did:

We have created a dummy plugin under metrics, for testing purposes, and wanted to use org.eclipse.jdt to
parse some java files when the run() method will be executed. We tried the execution of run() method by counting
the number of files for each ProjectVersion, and it worked as expected. Then, wee need to try the JDT AST parser
so reading AC documents we found out that we should create an external osgi bundle for that library. Here is what
we did:
1. Trying to create an external osgi bundle for: org.eclipse.jdt.core
   Dependency is as follows:
   
   ```
   <dependency>
       <groupId>org.eclipse.jdt</groupId>
       <artifactId>org.eclipse.jdt.core</artifactId>
       <version>3.7.1</version>
   </dependency> 
   ```

found it here: http://search.maven.org/#artifactdetails%7Corg.eclipse.jdt%7Corg.eclipse.jdt.core%7C3.7.1%7Cjar
We did it the easy way: 1) create a folder under external, 2) copy one of the available pom.xml (log4j), 3) change the 
values accordingly to match the new library, 4) update the external/pom.xml to add the module. After mvn install the
external module we created failed!
1. Trying to use < Embed-Dependency>, after failing with external bundle:

We modified the pom.xml of our plugin as follows:

```
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>eu.sqooss</groupId>
    <artifactId>metrics</artifactId>
    <version>0.95-SNAPSHOT</version>
  </parent>
  <groupId>gr.uom.alitheia</groupId>
  <artifactId>test-uom-metrics</artifactId>
  <version>0.1</version>
  <packaging>bundle</packaging>
  <name>Testing Metric Plugin in Alitheia Core by UoM</name>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <version>2.2.0</version>
        <extensions>true</extensions>
        <configuration>
          <instructions>
            <Embed-Dependency>*;scope=compile|runtime;artifactId=!core|org.osgi.core|org.osgi.compendium</Embed-Dependency>
            <Import-Package>*;resolution:=optional</Import-Package>
            <Export-Package>gr.uom.alitheia.metrics</Export-Package>
            <Bundle-Activator>gr.uom.alitheia.metrics.Activator</Bundle-Activator>
            <Bundle-SymbolicName>gr.uom.alitheia.metrics</Bundle-SymbolicName>
            <Bundle-Version>0.1</Bundle-Version>
            <Bundle-Vendor>gr.uom.alitheia</Bundle-Vendor>
            <Bundle-Description>gr.uom.alitheia.test-uom-metrics Alitheia Core metric</Bundle-Description>
          </instructions>
        </configuration>
      </plugin>
    </plugins>
  </build>
 <dependencies>
  <dependency>
        <groupId>eu.sqooss.alitheia</groupId>
        <artifactId>core</artifactId>
        <version>0.95-SNAPSHOT</version>
    </dependency>
    <dependency>
        <groupId>org.osgi</groupId>
        <artifactId>org.osgi.core</artifactId>
        <version>4.2.0</version>
        <optional>true</optional>
    </dependency>
    <dependency>
        <groupId>org.osgi</groupId>
        <artifactId>org.osgi.compendium</artifactId>
        <version>4.2.0</version>
        <optional>true</optional>
    </dependency>
    <dependency>
        <groupId>org.eclipse.jdt</groupId>
        <artifactId>org.eclipse.jdt.core</artifactId>
        <version>3.7.1</version>
    </dependency>
 <dependencies>
</project>
```
- Then we issue mvn install and everything worked. Then we tried to run AC, after the AC started it didn't listed
  our plugin at plugins tab!!! However no error was thrown, not or any warning, the logs tab showed < none>.
- In order to ensure that our plugin has not any issue, we just disabled the org.eclipse.jdt depndency and installed/
  executed AC again, and our plugin was present (already installed), we tried it and it worked.
- To ensure that we can use < Embed-Dendency> in our plugin we replaced org.eclipse.jdt dependency with
  the following:
  
  ```
  <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-math3</artifactId>
      <version>3.2</version>
  </dependency> 
  ```

and used some maths function of commons-math library within our plugin. We run the AC again and synchronized
the plugin (to invoke run() method) and everything worked, the math library was loaded and was used within run()
method.
- To be sure that org.eclipse.jdt dependency works great outside AC, we created a Maven project in Eclipse,
  specified the dependency and use AST parser to parse some java files.
- As it seems, we were able to use JDT with the specified dependency in a maven project outside AC and it 
  worked, we used <Embed-Dependency> for the math library with a maven dependency in AC and it worked, we 
  did the same for the JDT within AC and it didn't work, we tried to create an external bundle for it and it
  didn't work. So we would appreciate if you provide us with enough info in order to create the external bundle for
  the specified dependency (JDT) or with < Embed-Dependency>. It is very important to us to solve this issue
  because 90% of our metric's work is based on parsing source files, and without it we are stacked.

EDIT: It is very important to us to overcome this barrier because 90% of our metric's plugin depends on 
parsing source (java) files, so if you have any quick solution it would be a lifesaver. We would need to have a quick
solution to this problem in order to start our metric's plugin implementation asap; and in a foreseeable future you
can provide a full documentation on how to properly use external libraries. 
Thank you in advance.

**Comment by eligu** [comment] 2013-11-11 22:32
@modernist 
If you have tried it in the past (setting a dependency for one of your modules) why don't you try to create a very
simple metric plugin (5 secs) and specify JDT dependency I provide above (5 secs), install and pax:provision the
AC and see if it will load your plugin. I am pretty sure it will take you very little time to do it if you know how to, but 
it will save us hundred man's hour. Thank you in advance.

**Comment by modernist** [comment] 2013-11-11 23:41
I'm afraid there's no 'easy' or 'quick' solution - OSGi and maven have a learning curve that you have to climb. The only quick workaround I can think of is using the jdt OSGi bundle from here: http://repo1.maven.org/maven2/org/eclipse/jetty/orbit/org.eclipse.jdt.core/3.7.1/
(see the corresponding pom file for info on how to declare the dependency).

However, I think that most likely you don't need an OSGi bundle for jdt. The issue probably has something to do with an incorrect dependency or <code>Import</code> directive.

Setting the resolution of imported packages to 'optional' will allow your plugin to build successfully but it will likely fail to load properly due to the fact that the required dependencies are missing. 

After running <code>mvn pax:provision</code> you can use OSGi's <code>ss</code> command to view the list of installed bundles. Locate the ID of your failing bundle (it will be in the RESOLVED or INSTALLED state) and then issue the <code>diag [ID]</code> command to see which required dependencies are missing.

**Comment by eligu** [comment] 2013-11-11 23:55
@modernist Thank you very much for that info. I will try with the dependency you are referring, and see what can I do from osgi console.

**Comment by gousiosg** [comment] 2013-11-12 08:45
@eligu I think the problem is that `org.eclipse.jdt` is not a stand-alone jar and has transitive dependencies. 

Embedding dependencies in the generated OSGi bundle is configured through the `<Embed-Dependency>` rule. By default, it will include all dependencies whose scope is compile or runtime and do not start with org.osgi. To make the build system include all _transitive_ dependencies, you need to use the `<Embed-Transitive>` rule. See more about bundling here:

http://felix.apache.org/site/apache-felix-maven-bundle-plugin-bnd.html

Despite this, I would like to suggest that you start with resolving your dependencies one by one, using the process @modernist suggested, otherwise, you will end up with REALLY long build times.

As far as dependency embedding in AC, the rule is that if more than 1 plug-ins require a certain jar, this is bundled as a dependency in AC.

**Comment by eligu** [comment] 2013-11-12 15:30
@gousiosg 

Thank you for your response. I managed to add org.eclipse.jdt as a bundle under external. It builds correctly, so far no compile errors. I added the dependency on our metrics/plugin and when launching AC I did what @modernist 
described. As I checked I realize that our plugin is only Installed (not Active) same as org.eclipse.jdt. After checking
which dependencies were unresolved it shows some very cryptic ones (com.ibm.text etc). However we used 
org.eclipse.jdt in another maven project (no osgi) and it worked as expected. So I think there is something 
related to osgi, probably an optional dependency (I did all dependencies mandatory, to check if it will compile).
At this moment we can't do anything, so if you manage to set up org.eclipse.jdt in a dummy metric.plugin and
work with it, it would be very nice, to make a pull request to our plugin_exp_uom branch of forked by @teohaik 
AC. 

Thank you.

**Comment by teohaik** [comment] 2013-11-12 22:27
This problem is like the Lernaean Hydra. You cut one head and suddenly other 5 arise!

Working in parallalel with @eligu, I managed to find and import all the required jars as osgi bundles by searching in sites as http://search.maven.org/ and http://ebr.springsource.com/ ending up with a pom.xml with the following dependencies:

https://github.com/teohaik/Alitheia-Core/blob/plugin_exp_uom/metrics/test-uom-metrics/pom.xml

I tried many times with different combinations of dependencies. I added/removed many times, different dependencies.
In most cases the plugin was installed with no build errors but after running AC and hitting ss, and diag [code] I always find out that the plugin still had dependency issues. But the resolution of an issue usually cause other issues/conflicts! 
The final conflict is a NoClassDefFoundError  of org.apache.felix.shell.ShellService. 

In order to start with reductio ad absurdum to eliminate possible problems, please tell me, is this a correct approach to work? Are there any other configuration tricks that we should be aware of?

**Comment by gousiosg** [comment] 2013-11-13 08:25
Yes, unfortunately this is how it goes if you want to pull in complex, non-self-standing dependencies. It would be nice if you could share your fork somewhere so that I could have a look at your pom.

**Comment by teohaik** [comment] 2013-11-13 09:54
Of course! 
https://github.com/teohaik/Alitheia-Core/tree/plugin_exp_uom/metrics/test-uom-metrics

**Comment by teohaik** [comment] 2013-11-13 10:01
I had a mistake in the configuration section, just corrected it.

**Comment by gousiosg** [comment] 2013-11-13 10:18
Let me note here that this is not a technical support forum, but an issue tracker. As long as there is no problem with Alitheia Core, and in this case there is none, I consider this issue closed. SENSE AC overlords (@modernist, @mkechagia), do you agree?

**Comment by mkechagia** [comment] 2013-11-13 12:00
Right @gousiosg. Thanks a lot for the support!

**Closed as completed** 2013-11-13 14:27 UTC
